### ISSUE TITLE
Interesting effect found

### ISSUE THREAD

**Issue by GoTryCatch** [NMO13/earclipper#2]
Interesting effect found...

My simple code:

```
 List<Vector3m> points = new List<Vector3m>();
 //points.Add(new Vector3m(11.297915573061864, 108.74203291321881, 0)); // Uncomment this 
 points.Add(new Vector3m(10.67931514511419, 108.89208589551002, 0));
 points.Add(new Vector3m(10.063758632927504, 108.96680292510067, 0));
 points.Add(new Vector3m(9.487789694397, 109.023312456048, 0));
 points.Add(new Vector3m(9.487789694397, 109.023312456048, 2));
 points.Add(new Vector3m(10.063758632927511, 108.96680292510068, 2));
 points.Add(new Vector3m(10.679315145114197, 108.89208589551002, 2));
 //points.Add(new Vector3m(11.29791557306187, 108.74203291321881, 2)); // and this to take effect
            
 EarClipping earClipping = new EarClipping();
 earClipping.SetPoints(points);
 earClipping.Triangulate();
 var res = earClipping.Result;
 PrintTriangles(res);
```
Visualize triangulation with 6 points: All good
![Its OK For 6 Points](https://user-images.githubusercontent.com/94449956/162134817-f488bd0d-49a3-487f-a1df-cbd6575f3134.png)

Visualize triangulation with 8 points: 
![8 Points With Effect](https://user-images.githubusercontent.com/94449956/162135087-38176e55-9c62-43ad-b82f-8f16e2ffd38a.png)

My expectation:
![Its must be OK For 8 Points](https://user-images.githubusercontent.com/94449956/162135284-9900639f-6efa-4e9d-a8de-df0effbcf67f.png)

how can I fix the library, for my expectations?

**Comment by NMO13** [comment]
Thank you for sharing. I will have a look at it.

**Comment by GoTryCatch** [comment]
It would be great, thank you!!!

**Comment by NMO13** [comment]
@GoTryCatch your expectations are wrong. The middle vertices of your 8 point vertices are not collinear. They are forming convexities. Therefore the output of the triangulator is correct.

Here is your polygon, drawn very exaggeratingly so that it becomes clear what I mean:
![image](https://user-images.githubusercontent.com/3988444/169648978-ac92e5f6-78f2-4476-8c98-d720387e81da.png)

To proof that the implementation is correct, I have added another example which shows that collinearity is handled correctly.

Thank you anyway for your comment.
